spring:
  datasource:
    username: ziykrtutdxhfiz
    password: e172d0f9791ae3b0710b7899673bdfcffd04fa276b276d3e4bc3cdec50ce6320
    url: jdbc:postgresql://ec2-54-227-248-71.compute-1.amazonaws.com/d1c99rpckpqg2c
  sql:
    init:
      encoding: UTF-8
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        cache:
          use_second_level_cache: true
        region:
          factory_class: org.hibernate.cache.jcache.internal.JCacheRegionFactory
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    open-in-view: false
  cache:
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
      config: cache/ehcache.xml
  h2:
    console:
      enabled: true
